### ISSUE TITLE
'L' is not defined  no-undef

### ISSUE THREAD

**Issue by Elgert** [clflowers5/mapquest-js-react#1]
Hi,

Im trying to integrate your code into my reactjs project, but im getting this when running.

Do you have any idea why it happens ?

Failed to compile
./src/components/mapquest.js
  Line 25:  'L' is not defined  no-undef
  Line 27:  'L' is not defined  no-undef
  Line 29:  'L' is not defined  no-undef

Search for the keywords to learn more about each error.

**Comment by clflowers5** [comment]
The version of MapQuest-js included in the `lib` directory has Leaflet included, so `L` will be defined when `mapquest-js` is imported.

This looks like an ESLint error, in which case you can declare `L` as a global, something like this in your `.eslintrc` file:
```json
{
    "globals": {
        "L": true
    }
}
```

**Comment by YkBastidas** [comment]
> Hi,
> 
> Im trying to integrate your code into my reactjs project, but im getting this when running.
> 
> Do you have any idea why it happens ?
> 
> Failed to compile
> ./src/components/mapquest.js
> Line 25: 'L' is not defined no-undef
> Line 27: 'L' is not defined no-undef
> Line 29: 'L' is not defined no-undef
> 
> Search for the keywords to learn more about each error.

You can fix this using "window.L" cause the variable L is loading with the API, so if you don't declare it ESLint would detect it as it's not declared

**Comment by selvarajk2019** [comment]
Hi,

Im trying to integrate your code into my reactjs project, but im getting this when running.

Do you have any idea why it happens ?

Failed to compile
./src/components/mapquest.js
Line 25: 'L' is not defined no-undef
Line 27: 'L' is not defined no-undef
Line 29: 'L' is not defined no-undef

same issues am also looking, can you any one give clear idea of this work..
